name: Deploy GitHub Pages

on:
  push:
    branches: ["main"] # 监听 main 分支的动静

# 分配 Pages 的发布权限
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true # 重点：新推送来时，立刻掐断旧的发布，全力跑新的

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # 上传整个根目录（包含你的各个静态 HTML 目录）

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
